# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34d3928fa391fe6ca7fc3377d6c03366c29796a23c05d4b40dcfc321c1a63b67276ded2bf73bf12781251b89720b15d946c56918b6c8eeb8cebf1fa3e0585372

test:
  secret_key_base: c0a3dc49382c350a21adf0289ff4c8b63573e4458f0baafd2251ebcf445c1d8c9b73501eb1b2403707e5ac21d1a831f36ecd089746f7c1516fb762584cf104af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
